/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_TempMeter
#define HEADER_TempMeter
/*
htop - TempMeter.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.

This meter written by Patrick Louis < patrick at unixhub [dot] net >.
*/

int TempMeter_attributes[] ;

double getProcTempData(;

extern MeterType TempMeter;

#endif
